Repository openrewrite/rewrite-recipe-markdown-generator, pull requests merged in 2023-06, with the labels that each got.

#61 Specify that a recipe is a composite recipe
  src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Labels: documentation, enhancement

#64 Jackson BOM version 2.14.2 -> 2.15.2
  build.gradle.kts
Labels: dependencies

#63 Fix contributor email links
  src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Labels: bug
